### PR TITLE
Rewrite Dockerfile to use multi-stage build and Alpine 3.7

### PR DESCRIPTION
**Pull request by felipesantiago**

### CODE REVIEW

**Comment by csanders-git** [comment]
Generally looks like a good update. I feel like it's possible to remove some of the additional modules loaded by Apache.

**Comment by felipesantiago** [comment]
Yeah, it's definitely possible. I kept the default modules on httpd.conf from the Alpine's package.

**Comment by victorhora** [comment]
This is interesting. On a quick test here I managed to get a container with ~12MB in size. What you think about merging this one @csanders-git?

**Comment by csanders-git** [comment]
This looks good to me, are you planing on changing anything else otherwise i'll merge and build.

**Comment by felipesantiago** [comment]
Cool. 
I was planning to look at the other branches and see if there's room for improvement there, but for this branch I think we're good to go.

**Comment by csanders-git** [comment]
There is and I invite you to do so - thanks for the contribution.

**Comment by csanders-git** [comment]
Also feel free to make a contributors file and add yourself.

**Pull request merged**
