### PR TITLE
Add extended access.log

### PR DESCRIPTION
**Pull request by franbuehler**
Add extended log format access.log.
I will also provide a PR for the Core Rule Set docker container.
There, the timeout variables will be filled.

### CODE REVIEW

**Comment by dune73** [comment]
You are not using the latest version of the format. But otherwise, this looks good. Thank you for the links. :)

**Comment by franbuehler** [comment]
Where do I find the latest format?
:)

**Comment by dune73** [comment]
In the link you posted. :)

https://www.netnea.com/cms/apache-tutorial-5_extending-access-log/ - Step 4.

**Comment by franbuehler** [comment]
Log entry now looks like this:
```
127.0.0.1 - - [2019-06-21 06:28:52.834028] "GET / HTTP/1.1" 502 379 "-" "curl/7.54.0" "-" 57640 localhost 127.0.0.1 80 proxy-server - + "-" XQx5JBwxZULVe@LwPonAngAAAsA - - 8474 582 -% 59321410 - - - - - - -
```

**Comment by dune73** [comment]
LGTM. Thanks.

**Comment by csanders-git** [comment]
This works fine, generally if we are shifting to a format where we include files from this repo, we just need to make sure to cleanup the dockerhub repo.

**Pull request merged**
