### PR TITLE
Update Dockerfile: add access.log

### PR DESCRIPTION
**Pull request by franbuehler**
Add access.log to httpd.conf

### CODE REVIEW

**Comment by dune73** [comment]
May I propose the "extended" logformat?

**Comment by franbuehler** [comment]
You mean, your extended format from https://www.netnea.com/cms/apache-tutorial-5_extending-access-log/?

How should I add it?

1. Everything in Dockerfile:

```
RUN sed -i -e 's/#LoadModule unique_id_module/LoadModule unique_id_module/g' /usr/local/apache2/conf/httpd.conf && \
	sed -i -e 's/ServerTokens Full/ServerTokens Prod/g' /usr/local/apache2/conf/extra/httpd-default.conf && \
	echo "ErrorLog /var/log/apache2/error.log"                                        >>	/usr/local/apache2/conf/httpd.conf && \

	echo "LogFormat "%h %{GEOIP_COUNTRY_CODE}e %u [%{%Y-%m-%d %H:%M:%S}t.%{usec_frac}t] \"%r\" %>s %b \" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "\"%{Referer}i\" \"%{User-Agent}i\" \"%{Content-Type}i\" %{remote}p %v %A %p %R \" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "%{BALANCER_WORKER_ROUTE}e %X \"%{cookie}n\" %{UNIQUE_ID}e" >>	/usr/local/apache2/conf/httpd.conf && \
 	echo "%{SSL_PROTOCOL}x %{SSL_CIPHER}x \" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "%I %O %{ratio}n%% %D %{ModSecTimeIn}e %{ApplicationTime}e %{ModSecTimeOut}e \" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "%{ModSecAnomalyScoreInPLs}e %{ModSecAnomalyScoreOutPLs}e \" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "%{ModSecAnomalyScoreIn}e %{ModSecAnomalyScoreOut}e" extended" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "CustomLog        logs/access.log extended" >>	/usr/local/apache2/conf/httpd.conf && \
	echo "LoadModule security2_module /usr/local/apache2/modules/mod_security2.so"    >>	/usr/local/apache2/conf/httpd.conf && \
	echo "Include conf/extra/httpd-default.conf"   									                  >>	/usr/local/apache2/conf/httpd.conf && \
	echo "<IfModule security2_module>\nInclude /etc/modsecurity.d/include.conf\n</IfModule>" 	  >>	/usr/local/apache2/conf/httpd.conf && \
  echo "include \"/etc/modsecurity.d/modsecurity.conf\"" > /etc/modsecurity.d/include.conf && \
  echo "ServerName $SERVERNAME" 												 	                        >> 	/usr/local/apache2/conf/httpd.conf && \
  echo "hello world" > /usr/local/apache2/htdocs/index.html
```

OR:

2. make a new /usr/local/apache2/conf/extra/httpd-logging.conf and only add `Include` to Dockerfile

and add everything in this httpd-logging.conf file?

Number 2 would be more readable. But I am not sure if it's common to do it that way.

**Comment by dune73** [comment]
I do not like Includes very much, but your call.

Can you do a `<<EOF` construct? That would make it more readable I guess.

Also: Don't forget to add the ModSec rules that fill the variables. You can find it all in my tutorial number 7, step 3.

**Comment by franbuehler** [comment]
Unfortunately, the extended log format can not be defined, as the CRS rules are missing in this modsecurity container.

**Pull request closed without merging**
